# Generated by Django 4.0.5 on 2022-12-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', models.CharField(max_length=10, null=True)),
                ('boy_name', models.CharField(max_length=100, null=True)),
                ('boy_mob', models.CharField(max_length=100, null=True)),
                ('boy_vehicle', models.CharField(max_length=100, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menuitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(default='', upload_to='items/images')),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('Chinese', 'Chinese'), ('South Indian', 'South Indian'), ('Breakfast', 'Breakfast'), ('Ice Cream', 'Ice Cream'), ('Sweets', 'Sweets'), ('Beverage', 'Beverage'), ('Italian', 'Italian'), ('Soups', 'Soups'), ('Starters', 'Starters'), ('Tandoors', 'Tandoors'), ('Main Course', 'Main Course'), ('Rice & Biryanis', 'Rice & Biryanis'), ('Bread', 'Bread'), ('Pizza and Burgers', 'Pizza and Burgers')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
