# Generated by Django 4.0.5 on 2022-12-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0002_deliveryboy_enp_id_deliveryboy_is_occupied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.DeleteModel(
            name='Menuitems',
        ),
        migrations.DeleteModel(
            name='RestAddress',
        ),
    ]
